In [1]:
!pip install gensim

In [2]:
import gensim
from gensim.models import word2vec,keyedvectors

In [3]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

In [4]:
vec_king.shape

(300,)

In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

### We are using same dataset for analysis and building model using word to vec:

In [6]:
import pandas as pd

In [7]:
messages = pd.read_csv('smsspamcollection/SMSSpamCollection', sep='\t', names=['label','message'])

In [8]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [9]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [10]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Administrator\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [12]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [13]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
words =[]
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [15]:
words    #we get list of every sentence in the corpus

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [16]:
len(words)

5569

In [17]:
import gensim

### Lets train word2vec from scratch

In [18]:
model = gensim.models.Word2Vec(words)

### To get all the vocabulary:

In [19]:
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope

In [20]:
model.corpus_count

5569

In [21]:
model.epochs  #The number of training passes (epochs) the model is configured to run over the corpus.

5

In [22]:
model.wv.similar_by_word('kid')

[('even', 0.9980013966560364),
 ('into', 0.9979139566421509),
 ('over', 0.9979020953178406),
 ('smile', 0.9978107810020447),
 ('were', 0.9977980852127075),
 ('fine', 0.9977886080741882),
 ('today', 0.9977828860282898),
 ('down', 0.9977811574935913),
 ('never', 0.9977794289588928),
 ('without', 0.9977541565895081)]

In [23]:
model.wv.similar_by_word('sport')


[('game', 0.9964789748191833),
 ('number', 0.9963562488555908),
 ('sm', 0.996356189250946),
 ('orange', 0.9963226914405823),
 ('mate', 0.9963026642799377),
 ('pic', 0.996263325214386),
 ('collection', 0.996235191822052),
 ('no', 0.9962083697319031),
 ('music', 0.9961835741996765),
 ('com', 0.9961665272712708)]

In [24]:
model.wv.similar_by_word('good') 
# Find the words whose vectors are most similar to the vector of the word 'sport'.


[('all', 0.998341977596283),
 ('about', 0.9982815384864807),
 ('morning', 0.9982435703277588),
 ('oh', 0.9981926083564758),
 ('got', 0.9981848001480103),
 ('happy', 0.998170018196106),
 ('where', 0.9981377720832825),
 ('very', 0.9980969429016113),
 ('night', 0.9980951547622681),
 ('wa', 0.9980869293212891)]

In [25]:
model.wv['good']
# Give me the numerical vector (embedding) learned for the word 'good'.

array([-2.6024771e-01,  3.4219712e-01,  5.7285037e-03,  1.8208882e-01,
        2.8916373e-05, -6.3673657e-01,  1.5457104e-01,  7.6488054e-01,
       -4.6616104e-01, -1.9263758e-01, -2.7963901e-01, -6.4466554e-01,
        1.8583165e-02,  1.5075235e-01,  1.7491169e-01, -3.4293208e-01,
        1.7351075e-01, -4.2457339e-01,  9.0154018e-03, -7.4438328e-01,
        4.0140489e-01,  3.0659482e-01,  1.9017169e-01, -2.6305044e-01,
       -2.0851487e-01, -5.5636231e-02, -3.4715533e-01, -2.6004907e-01,
       -4.9550682e-01,  4.1532587e-02,  4.2418951e-01, -8.0702156e-02,
        1.1957321e-01, -4.8639792e-01, -1.9014443e-01,  4.8649073e-01,
        2.0280743e-03, -3.0053458e-01, -2.1444352e-01, -6.3802642e-01,
        1.4752400e-01, -3.0961800e-01, -3.2841396e-01,  1.7633177e-02,
        3.5492018e-01, -5.7460193e-02, -3.0240077e-01, -1.7187920e-01,
        9.2965379e-02,  2.2168402e-01,  2.5370669e-01, -2.5606522e-01,
       -1.5096408e-01, -2.2528213e-02, -7.6206103e-02,  2.5267860e-01,
      

In [26]:
model.wv['good'].shape

(100,)

In [27]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

### tqdm is a progress-bar library — simple, powerful, and perfect for long loops.


In [28]:
!pip install tqdm 

In [29]:
from tqdm import tqdm

In [30]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

C:\Users\Administrator\anaconda3\Lib\site-packages\numpy\_core\fromnumeric.py:3904: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Administrator\anaconda3\Lib\site-packages\numpy\_core\_methods.py:147: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:02<00:00, 2090.44it/s]


In [31]:
X  #showing 100 dimensions for each sentence

[array([-0.17724903,  0.22038671,  0.01404068,  0.13045208,  0.00570828,
        -0.4538888 ,  0.10349133,  0.5134176 , -0.32140848, -0.13906257,
        -0.20265318, -0.41920632, -0.02784707,  0.10104985,  0.12730484,
        -0.23351888,  0.11304556, -0.29698056,  0.00678409, -0.5116875 ,
         0.23106124,  0.20129804,  0.11693963, -0.1791744 , -0.14148034,
        -0.03374099, -0.26595676, -0.17956635, -0.33336443,  0.03836465,
         0.29281044, -0.03941307,  0.0718222 , -0.32476744, -0.13293275,
         0.33596814,  0.02274931, -0.21891356, -0.1656749 , -0.4426162 ,
         0.1013317 , -0.22367294, -0.23845464, -0.00230576,  0.25023547,
        -0.05175348, -0.20136672, -0.1007304 ,  0.08894391,  0.15704486,
         0.14217396, -0.18664904, -0.07861829,  0.02135134, -0.08790774,
         0.17644933,  0.19889446,  0.07780537, -0.38867414,  0.07708593,
        -0.03406996,  0.11354836, -0.071908  , -0.13836965, -0.2863771 ,
         0.2817951 ,  0.05732472,  0.1555507 , -0.3

In [32]:
len(X)

5569

### Independant feature

In [33]:
X_new = np.array(X,dtype=object)

In [34]:
X_new.shape

(5569,)

In [35]:
X_new[0]   #first sentence

array([-0.17724903,  0.22038671,  0.01404068,  0.13045208,  0.00570828,
       -0.4538888 ,  0.10349133,  0.5134176 , -0.32140848, -0.13906257,
       -0.20265318, -0.41920632, -0.02784707,  0.10104985,  0.12730484,
       -0.23351888,  0.11304556, -0.29698056,  0.00678409, -0.5116875 ,
        0.23106124,  0.20129804,  0.11693963, -0.1791744 , -0.14148034,
       -0.03374099, -0.26595676, -0.17956635, -0.33336443,  0.03836465,
        0.29281044, -0.03941307,  0.0718222 , -0.32476744, -0.13293275,
        0.33596814,  0.02274931, -0.21891356, -0.1656749 , -0.4426162 ,
        0.1013317 , -0.22367294, -0.23845464, -0.00230576,  0.25023547,
       -0.05175348, -0.20136672, -0.1007304 ,  0.08894391,  0.15704486,
        0.14217396, -0.18664904, -0.07861829,  0.02135134, -0.08790774,
        0.17644933,  0.19889446,  0.07780537, -0.38867414,  0.07708593,
       -0.03406996,  0.11354836, -0.071908  , -0.13836965, -0.2863771 ,
        0.2817951 ,  0.05732472,  0.1555507 , -0.33442384,  0.32

In [36]:
X_new[0].shape   #sentence 1 and has 100 dimensions

(100,)

In [37]:
messages.shape

(5572, 2)

### Here messages and X_new has different shape. 